name: Automerge

on:
  pull_request_target:
    types: [opened, reopened, labeled, synchronize]
  workflow_run:
    workflows: ["British English Spelling Check"]
    types: [completed]
  workflow_dispatch:
    inputs:
      pull_numbers:
        description: 'PR numbers to merge (e.g. 1, 2, 3)'
        required: false
        type: string

permissions:
  pull-requests: write
  contents: write
  checks: read
  statuses: read

jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      pr_numbers: ${{ steps.check.outputs.pr_numbers }}
      should_merge: ${{ steps.check.outputs.should_merge }}
    steps:
      - name: Inspect PR author/labels
        id: check
        uses: actions/github-script@v6
        env:
          PULL_NUMBERS: ${{ github.event.inputs.pull_numbers }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            let prNumbers = [];
            
            if (process.env.PULL_NUMBERS) {
              prNumbers = process.env.PULL_NUMBERS
                .split(/[,\s]+/)
                .map(n => parseInt(n.trim(), 10))
                .filter(n => !isNaN(n));
            } else if (context.payload.pull_request && context.payload.pull_request.number) {
              prNumbers = [context.payload.pull_request.number];
            }
            
            if (prNumbers.length === 0) {
              core.info('No PR numbers found, scanning open PRs with automerge label.');
              try {
                const issues = await github.rest.issues.listForRepo({
                  owner,
                  repo,
                  state: 'open',
                  labels: 'automerge',
                  per_page: 100
                });
                prNumbers = issues.data
                  .filter(issue => issue.pull_request)
                  .map(issue => issue.number);
              } catch (error) {
                core.info(`Failed to list PRs by label: ${error.message}`);
              }
            }

            if (prNumbers.length === 0) {
              core.info('No PR numbers found.');
              core.setOutput('pr_numbers', '[]');
              core.setOutput('should_merge', 'false');
              return;
            }

            const validPRs = [];
            for (const prNum of prNumbers) {
              try {
                const prRes = await github.rest.pulls.get({ owner, repo, pull_number: prNum });
                const pr = prRes.data;
                const author = pr.user && pr.user.login;
                const labels = (pr.labels || []).map(l => l.name);
                const isDependabot = author === 'dependabot[bot]';
                const isRepoOwner = author === owner;
                const isCloudflare = author === 'cloudflare-workers-and-pages[bot]';
                const isPages = author === 'github-pages[bot]' || author === 'github-pages-deploy-action[bot]';
                const isGitHubActions = author === 'github-actions[bot]';
                const isLabel = labels.includes('automerge');
                const isTrustedAuthor = isDependabot || isRepoOwner || isCloudflare || isPages || isGitHubActions;

                if (isLabel && isTrustedAuthor) {
                  validPRs.push(prNum);
                  core.info(`PR #${prNum} valid (author=${author}, label=automerge, isDependabot=${isDependabot}, isRepoOwner=${isRepoOwner}, isCloudflare=${isCloudflare}, isPages=${isPages}, isGitHubActions=${isGitHubActions})`);
                } else {
                  core.info(`PR #${prNum} skipped (requires automerge label AND trusted author - hasLabel=${isLabel}, isTrusted=${isTrustedAuthor})`);
                }
              } catch (error) {
                core.info(`PR #${prNum} not found or error: ${error.message}`);
              }
            }
            
            core.setOutput('pr_numbers', JSON.stringify(validPRs));
            core.setOutput('should_merge', String(validPRs.length > 0));


  automerge-dependabot:
    needs: guard
    if: needs.guard.outputs.should_merge == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets['{{BOT_APP_ID_SECRET}}'] }}
          private-key: ${{ secrets['{{BOT_PRIVATE_KEY_SECRET}}'] }}
      - name: Merge PRs
        uses: actions/github-script@v6
        env:
          PR_NUMBERS: ${{ needs.guard.outputs.pr_numbers }}
        with:
          github-token: ${{ steps.app_token.outputs.token }}
          script: |
            const { owner, repo } = context.repo;
            const prNumbers = JSON.parse(process.env.PR_NUMBERS || '[]');
            
            for (const prNumber of prNumbers) {
              try {
                await github.rest.pulls.merge({ owner, repo, pull_number: prNumber });
                core.info(`Merged PR #${prNumber}`);
              } catch (error) {
                core.setFailed(`Failed to merge PR #${prNumber}: ${error.message}`);
              }
            }
