name: Automerge

on:
  pull_request_target:
    types: [opened, reopened, labeled, synchronize]
  workflow_run:
    workflows: ["British English Spelling Check"]
    types: [completed]
  workflow_dispatch:
    inputs:
      pull_numbers:
        description: 'PR numbers to merge (e.g. 1, 2, 3)'
        required: false
        type: string

permissions:
  pull-requests: write
  contents: write
  checks: read
  statuses: read

jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      pr_numbers: ${{ steps.check.outputs.pr_numbers }}
      should_merge: ${{ steps.check.outputs.should_merge }}
    steps:
      - name: Inspect PR author/labels
        id: check
        uses: actions/github-script@v6
        env:
          PULL_NUMBERS: ${{ github.event.inputs.pull_numbers }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            let prNumbers = [];
            
            if (process.env.PULL_NUMBERS) {
              prNumbers = process.env.PULL_NUMBERS
                .split(/[,\s]+/)
                .map(n => parseInt(n.trim(), 10))
                .filter(n => !isNaN(n));
            } else if (context.payload.pull_request && context.payload.pull_request.number) {
              prNumbers = [context.payload.pull_request.number];
            }
            
            if (prNumbers.length === 0) {
              core.info('No PR numbers found, scanning open PRs with automerge label.');
              try {
                const issues = await github.rest.issues.listForRepo({
                  owner,
                  repo,
                  state: 'open',
                  labels: 'automerge',
                  per_page: 100
                });
                prNumbers = issues.data
                  .filter(issue => issue.pull_request)
                  .map(issue => issue.number);
              } catch (error) {
                core.info(`Failed to list PRs by label: ${error.message}`);
              }
            }

            if (prNumbers.length === 0) {
              core.info('No PR numbers found.');
              core.setOutput('pr_numbers', '[]');
              core.setOutput('should_merge', 'false');
              return;
            }

            const validPRs = [];
            for (const prNum of prNumbers) {
              try {
                const prRes = await github.rest.pulls.get({ owner, repo, pull_number: prNum });
                const pr = prRes.data;
                const author = pr.user && pr.user.login;
                const labels = (pr.labels || []).map(l => l.name);
                const isDependabot = author === 'dependabot[bot]';
                const isRepoOwner = author === owner;
                const isCloudflare = author === 'cloudflare-workers-and-pages[bot]';
                const isPages = author === 'github-pages[bot]' || author === 'github-pages-deploy-action[bot]';
                const isGitHubActions = author === 'github-actions[bot]';
                const isLabel = labels.includes('automerge');
                const isTrustedAuthor = isDependabot || isRepoOwner || isCloudflare || isPages || isGitHubActions;

                if (isLabel && isTrustedAuthor) {
                  validPRs.push(prNum);
                  core.info(`PR #${prNum} valid (author=${author}, label=automerge, isDependabot=${isDependabot}, isRepoOwner=${isRepoOwner}, isCloudflare=${isCloudflare}, isPages=${isPages}, isGitHubActions=${isGitHubActions})`);
                } else {
                  core.info(`PR #${prNum} skipped (requires automerge label AND trusted author - hasLabel=${isLabel}, isTrusted=${isTrustedAuthor})`);
                }
              } catch (error) {
                core.info(`PR #${prNum} not found or error: ${error.message}`);
              }
            }
            
            core.setOutput('pr_numbers', JSON.stringify(validPRs));
            core.setOutput('should_merge', String(validPRs.length > 0));


  automerge-dependabot:
    needs: guard
    if: needs.guard.outputs.should_merge == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets['{{BOT_APP_ID_SECRET}}'] }}
          private-key: ${{ secrets['{{BOT_PRIVATE_KEY_SECRET}}'] }}
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - name: Setup bot identity
        id: identity
        uses: XAOSTECH/dev-control/.github/actions/identity@main
        with:
          gpg-private-key: ${{ secrets['{{GPG_PRIVATE_KEY_SECRET}}'] }}
          gpg-passphrase: ${{ secrets['{{GPG_PASSPHRASE_SECRET}}'] }}
          user-token: ${{ secrets['{{USER_TOKEN_SECRET}}'] }}
          bot-name: ${{ vars.BOT_NAME || '{{BOT_NAME}}' }}

      - name: Merge PRs with signed commits
        if: steps.identity.outputs.gpg-outcome == 'success'
        env:
          PR_NUMBERS: ${{ needs.guard.outputs.pr_numbers }}
        run: |
          set -euo pipefail
          pr_numbers=$(echo "$PR_NUMBERS" | tr -d '[]' | tr ',' ' ')
          for pr_number in $pr_numbers; do
            echo "🔀 Merging PR #${pr_number} with signed commit"
            pr_json=$(gh api "repos/${GITHUB_REPOSITORY}/pulls/${pr_number}")
            base_ref=$(echo "$pr_json" | jq -r '.base.ref')
            head_sha=$(echo "$pr_json" | jq -r '.head.sha')

            git fetch origin "$base_ref"
            git checkout -B "$base_ref" "origin/$base_ref"
            git fetch origin "pull/${pr_number}/head":"refs/remotes/pr/${pr_number}"

            if ! git merge --no-ff --no-edit "refs/remotes/pr/${pr_number}"; then
              echo "❌ Merge conflict for PR #${pr_number}. Aborting."
              git merge --abort || true
              exit 1
            fi

            # Confirm we merged the intended head
            if ! git log -1 --pretty=%B | grep -q "${head_sha}"; then
              echo "ℹ️ Merge commit created; pushing to ${base_ref}"
            fi

            git push origin "$base_ref"
          done

      - name: Merge PRs via API (fallback)
        if: steps.identity.outputs.gpg-outcome != 'success'
        uses: actions/github-script@v6
        env:
          PR_NUMBERS: ${{ needs.guard.outputs.pr_numbers }}
        with:
          github-token: ${{ steps.app_token.outputs.token }}
          script: |
            const { owner, repo } = context.repo;
            const prNumbers = JSON.parse(process.env.PR_NUMBERS || '[]');
            for (const prNumber of prNumbers) {
              try {
                await github.rest.pulls.merge({ owner, repo, pull_number: prNumber });
                core.info(`Merged PR #${prNumber} via API fallback`);
              } catch (error) {
                core.setFailed(`Failed to merge PR #${prNumber}: ${error.message}`);
              }
            }
